<?php  
html::title('Время и дата');
livecms_header();
access('users');

if (post('ok_tm')){
  
  valid::create(array(
    
    'TIMEZONE' => ['timezone', 'text', [1,200], 'Временная зона', 0]
  
  ));
  
  db::get_set("UPDATE `USERS` SET `TIMEZONE` = ? WHERE `ID` = ? LIMIT 1", [TIMEZONE, user('ID')]);
  
  success('Измнения успешно приняты');
  redirect('/account/settings/timedate/');
  
}

?>
<div class='list'>
<form method='post' class='ajax-form' action='/account/settings/timedate/'>
<?=html::select('timezone', array(  
 'Africa/Abidjan' => ['Africa/Abidjan', (user('TIMEZONE') == 'Africa/Abidjan' ? "selected" : null)],
 'Africa/Asmara' => ['Africa/Asmara', (user('TIMEZONE') == 'Africa/Asmara' ? "selected" : null)],
 'Africa/Bissau' => ['Africa/Bissau', (user('TIMEZONE') == 'Africa/Bissau' ? "selected" : null)],
 'Africa/Cairo' => ['Africa/Cairo', (user('TIMEZONE') == 'Africa/Cairo' ? "selected" : null)],
 'Africa/Dakar' => ['Africa/Dakar', (user('TIMEZONE') == 'Africa/Dakar' ? "selected" : null)],
 'Africa/El_Aaiun' => ['Africa/El_Aaiun', (user('TIMEZONE') == 'Africa/El_Aaiun' ? "selected" : null)],
 'Africa/Johannesburg' => ['Africa/Johannesburg', (user('TIMEZONE') == 'Africa/Johannesburg' ? "selected" : null)],
 'Africa/Kigali' => ['Africa/Kigali', (user('TIMEZONE') == 'Africa/Kigali' ? "selected" : null)],
 'Africa/Lome' => ['Africa/Lome', (user('TIMEZONE') == 'Africa/Lome' ? "selected" : null)],
 'Africa/Malabo' => ['Africa/Malabo', (user('TIMEZONE') == 'Africa/Malabo' ? "selected" : null)],
 'Africa/Mogadishu' => ['Africa/Mogadishu', (user('TIMEZONE') == 'Africa/Mogadishu' ? "selected" : null)],
 'Africa/Niamey' => ['Africa/Niamey', (user('TIMEZONE') == 'Africa/Niamey' ? "selected" : null)],
 'Africa/Sao_Tome' => ['Africa/Sao_Tome', (user('TIMEZONE') == 'Africa/Sao_Tome' ? "selected" : null)],
 'Africa/Accra' => ['Africa/Accra', (user('TIMEZONE') == 'Africa/Accra' ? "selected" : null)],
 'Africa/Bamako' => ['Africa/Bamako', (user('TIMEZONE') == 'Africa/Bamako' ? "selected" : null)],
 'Africa/Blantyre' => ['Africa/Blantyre', (user('TIMEZONE') == 'Africa/Blantyre' ? "selected" : null)],
 'America/Adak' => ['America/Adak', (user('TIMEZONE') == 'America/Adak' ? "selected" : null)],
 'America/Araguaina' => ['America/Araguaina', (user('TIMEZONE') == 'America/Araguaina' ? "selected" : null)],
 'America/Argentina/Jujuy' => ['America/Argentina/Jujuy', (user('TIMEZONE') == 'America/Argentina/Jujuy' ? "selected" : null)],
 'America/Argentina/Salta' => ['America/Argentina/Salta', (user('TIMEZONE') == 'America/Argentina/Salta' ? "selected" : null)],
 'America/Argentina/Ushuaia' => ['America/Argentina/Ushuaia', (user('TIMEZONE') == 'America/Argentina/Ushuaia' ? "selected" : null)],
 'America/Bahia' => ['America/Bahia', (user('TIMEZONE') == 'America/Bahia' ? "selected" : null)],
 'America/Belize' => ['America/Belize', (user('TIMEZONE') == 'America/Belize' ? "selected" : null)],
 'America/Boise' => ['America/Boise', (user('TIMEZONE') == 'America/Boise' ? "selected" : null)],
 'America/Caracas' => ['America/Caracas', (user('TIMEZONE') == 'America/Caracas' ? "selected" : null)],
 'America/Chihuahua' => ['America/Chihuahua', (user('TIMEZONE') == 'America/Chihuahua' ? "selected" : null)],
 'America/Curacao' => ['America/Curacao', (user('TIMEZONE') == 'America/Curacao' ? "selected" : null)],
 'America/Denver' => ['America/Denver', (user('TIMEZONE') == 'America/Denver' ? "selected" : null)],
 'America/Eirunepe' => ['America/Eirunepe', (user('TIMEZONE') == 'America/Eirunepe' ? "selected" : null)],
 'America/Glace_Bay' => ['America/Glace_Bay', (user('TIMEZONE') == 'America/Glace_Bay' ? "selected" : null)],
 'America/Guadeloupe' => ['America/Guadeloupe', (user('TIMEZONE') == 'America/Guadeloupe' ? "selected" : null)],
 'America/Halifax' => ['America/Halifax', (user('TIMEZONE') == 'America/Halifax' ? "selected" : null)],
 'America/Indiana/Knox' => ['America/Indiana/Knox', (user('TIMEZONE') == 'America/Indiana/Knox' ? "selected" : null)],
 'America/Indiana/Vevay' => ['America/Indiana/Vevay', (user('TIMEZONE') == 'America/Indiana/Vevay' ? "selected" : null)],
 'America/Iqaluit' => ['America/Iqaluit', (user('TIMEZONE') == 'America/Iqaluit' ? "selected" : null)],
 'America/Kentucky/Monticello' => ['America/Kentucky/Monticello', (user('TIMEZONE') == 'America/Kentucky/Monticello' ? "selected" : null)],
 'America/Los_Angeles' => ['America/Los_Angeles', (user('TIMEZONE') == 'America/Los_Angeles' ? "selected" : null)],
 'Antarctica/Casey' => ['Antarctica/Casey', (user('TIMEZONE') == 'Antarctica/Casey' ? "selected" : null)],
 'Antarctica/Mawson' => ['Antarctica/Mawson', (user('TIMEZONE') == 'Antarctica/Mawson' ? "selected" : null)],
 'Antarctica/Syowa' => ['Antarctica/Syowa', (user('TIMEZONE') == 'Antarctica/Syowa' ? "selected" : null)],
 'Antarctica/Davis' => ['Antarctica/Davis', (user('TIMEZONE') == 'Antarctica/Davis' ? "selected" : null)],
 'Antarctica/McMurdo' => ['Antarctica/McMurdo', (user('TIMEZONE') == 'Antarctica/McMurdo' ? "selected" : null)],
 'Antarctica/Troll' => ['Antarctica/Troll', (user('TIMEZONE') == 'Antarctica/Troll' ? "selected" : null)],
 'Antarctica/DumontDUrville' => ['Antarctica/DumontDUrville', (user('TIMEZONE') == 'Antarctica/DumontDUrville' ? "selected" : null)],
 'Antarctica/Palmer' => ['Antarctica/Palmer', (user('TIMEZONE') == 'Antarctica/Palmer' ? "selected" : null)],
 'Antarctica/Vostok' => ['Antarctica/Vostok', (user('TIMEZONE') == 'Antarctica/Vostok' ? "selected" : null)],
 'Antarctica/Macquarie' => ['Antarctica/Macquarie', (user('TIMEZONE') == 'Antarctica/Macquarie' ? "selected" : null)],
 'Antarctica/Rothera' => ['Antarctica/Rothera', (user('TIMEZONE') == 'Antarctica/Rothera' ? "selected" : null)],
 'Arctic/Longyearbyen' => ['Arctic/Longyearbyen', (user('TIMEZONE') == 'Arctic/Longyearbyen' ? "selected" : null)],
 'Asia/Aden' => ['Asia/Aden', (user('TIMEZONE') == 'Asia/Aden' ? "selected" : null)],
 'Asia/Aqtau' => ['Asia/Aqtau', (user('TIMEZONE') == 'Asia/Aqtau' ? "selected" : null)],
 'Asia/Baghdad' => ['Asia/Baghdad', (user('TIMEZONE') == 'Asia/Baghdad' ? "selected" : null)],
 'Asia/Barnaul' => ['Asia/Barnaul', (user('TIMEZONE') == 'Asia/Barnaul' ? "selected" : null)],
 'Asia/Chita' => ['Asia/Chita', (user('TIMEZONE') == 'Asia/Chita' ? "selected" : null)],
 'Asia/Dhaka' => ['Asia/Dhaka', (user('TIMEZONE') == 'Asia/Dhaka' ? "selected" : null)],
 'Asia/Famagusta' => ['Asia/Famagusta', (user('TIMEZONE') == 'Asia/Famagusta' ? "selected" : null)],
 'Asia/Hong_Kong' => ['Asia/Hong_Kong', (user('TIMEZONE') == 'Asia/Hong_Kong' ? "selected" : null)],
 'Asia/Jayapura' => ['Asia/Jayapura', (user('TIMEZONE') == 'Asia/Jayapura' ? "selected" : null)],
 'Asia/Karachi' => ['Asia/Karachi', (user('TIMEZONE') == 'Asia/Karachi' ? "selected" : null)],
 'Asia/Krasnoyarsk' => ['Asia/Krasnoyarsk', (user('TIMEZONE') == 'Asia/Krasnoyarsk' ? "selected" : null)],
 'Asia/Macau' => ['Asia/Macau', (user('TIMEZONE') == 'Asia/Macau' ? "selected" : null)],
 'Asia/Muscat' => ['Asia/Muscat', (user('TIMEZONE') == 'Asia/Muscat' ? "selected" : null)],
 'Asia/Omsk' => ['Asia/Omsk', (user('TIMEZONE') == 'Asia/Omsk' ? "selected" : null)],
 'Asia/Pyongyang' => ['Asia/Pyongyang', (user('TIMEZONE') == 'Asia/Pyongyang' ? "selected" : null)],
 'Asia/Riyadh' => ['Asia/Riyadh', (user('TIMEZONE') == 'Asia/Riyadh' ? "selected" : null)],
 'Asia/Shanghai' => ['Asia/Shanghai', (user('TIMEZONE') == 'Asia/Shanghai' ? "selected" : null)],
 'Asia/Tashkent' => ['Asia/Tashkent', (user('TIMEZONE') == 'Asia/Tashkent' ? "selected" : null)],
 'Asia/Tokyo' => ['Asia/Tokyo', (user('TIMEZONE') == 'Asia/Tokyo' ? "selected" : null)],
 'Asia/Ust-Nera' => ['Asia/Ust-Nera', (user('TIMEZONE') == 'Asia/Ust-Nera' ? "selected" : null)],
 'Asia/Yangon' => ['Asia/Yangon', (user('TIMEZONE') == 'Asia/Yangon' ? "selected" : null)],
 'Asia/Almaty' => ['Asia/Almaty', (user('TIMEZONE') == 'Asia/Almaty' ? "selected" : null)],
 'Asia/Aqtobe' => ['Asia/Aqtobe', (user('TIMEZONE') == 'Asia/Aqtobe' ? "selected" : null)],
 'Asia/Bahrain' => ['Asia/Bahrain', (user('TIMEZONE') == 'Asia/Bahrain' ? "selected" : null)],
 'Asia/Beirut' => ['Asia/Beirut', (user('TIMEZONE') == 'Asia/Beirut' ? "selected" : null)],
 'Asia/Choibalsan' => ['Asia/Choibalsan', (user('TIMEZONE') == 'Asia/Choibalsan' ? "selected" : null)],
 'Asia/Dili' => ['Asia/Dili', (user('TIMEZONE') == 'Asia/Dili' ? "selected" : null)],
 'Asia/Gaza' => ['Asia/Gaza', (user('TIMEZONE') == 'Asia/Gaza' ? "selected" : null)],
 'Asia/Hovd' => ['Asia/Hovd', (user('TIMEZONE') == 'Asia/Hovd' ? "selected" : null)],
 'Asia/Jerusalem' => ['Asia/Jerusalem', (user('TIMEZONE') == 'Asia/Jerusalem' ? "selected" : null)],
 'Asia/Kathmandu' => ['Asia/Kathmandu', (user('TIMEZONE') == 'Asia/Kathmandu' ? "selected" : null)],
 'Asia/Kuala_Lumpur' => ['Asia/Kuala_Lumpur', (user('TIMEZONE') == 'Asia/Kuala_Lumpur' ? "selected" : null)],
 'Asia/Magadan' => ['Asia/Magadan', (user('TIMEZONE') == 'Asia/Magadan' ? "selected" : null)],
 'Asia/Nicosia' => ['Asia/Nicosia', (user('TIMEZONE') == 'Asia/Nicosia' ? "selected" : null)],
 'Asia/Oral' => ['Asia/Oral', (user('TIMEZONE') == 'Asia/Oral' ? "selected" : null)],
 'Asia/Qatar' => ['Asia/Qatar', (user('TIMEZONE') == 'Asia/Qatar' ? "selected" : null)],
 'Asia/Sakhalin' => ['Asia/Sakhalin', (user('TIMEZONE') == 'Asia/Sakhalin' ? "selected" : null)],
 'Asia/Singapore' => ['Asia/Singapore', (user('TIMEZONE') == 'Asia/Singapore' ? "selected" : null)],
 'Asia/Tbilisi' => ['Asia/Tbilisi', (user('TIMEZONE') == 'Asia/Tbilisi' ? "selected" : null)],
 'Asia/Tel_Aviv' => ['Asia/Tel_Aviv', (user('TIMEZONE') == 'Asia/Tel_Aviv' ? "selected" : null)], 
 'Asia/Tomsk' => ['Asia/Tomsk', (user('TIMEZONE') == 'Asia/Tomsk' ? "selected" : null)],
 'Asia/Vientiane' => ['Asia/Vientiane', (user('TIMEZONE') == 'Asia/Vientiane' ? "selected" : null)],
 'Asia/Yekaterinburg' => ['Asia/Yekaterinburg', (user('TIMEZONE') == 'Asia/Yekaterinburg' ? "selected" : null)],
 'Asia/Amman' => ['Asia/Amman', (user('TIMEZONE') == 'Asia/Amman' ? "selected" : null)],
 'Asia/Ashgabat' => ['Asia/Ashgabat', (user('TIMEZONE') == 'Asia/Ashgabat' ? "selected" : null)],
 'Asia/Baku' => ['Asia/Baku', (user('TIMEZONE') == 'Asia/Baku' ? "selected" : null)],
 'Asia/Bishkek' => ['Asia/Bishkek', (user('TIMEZONE') == 'Asia/Bishkek' ? "selected" : null)],
 'Asia/Colombo' => ['Asia/Colombo', (user('TIMEZONE') == 'Asia/Colombo' ? "selected" : null)],
 'Asia/Dubai' => ['Asia/Dubai', (user('TIMEZONE') == 'Asia/Dubai' ? "selected" : null)],
 'Asia/Hebron' => ['Asia/Hebron', (user('TIMEZONE') == 'Asia/Hebron' ? "selected" : null)],
 'Asia/Irkutsk' => ['Asia/Irkutsk', (user('TIMEZONE') == 'Asia/Irkutsk' ? "selected" : null)],
 'Asia/Kabul' => ['Asia/Kabul', (user('TIMEZONE') == 'Asia/Kabul' ? "selected" : null)],
 'Asia/Khandyga' => ['Asia/Khandyga', (user('TIMEZONE') == 'Asia/Khandyga' ? "selected" : null)],
 'Asia/Kuching' => ['Asia/Kuching', (user('TIMEZONE') == 'Asia/Kuching' ? "selected" : null)],
 'Asia/Makassar' => ['Asia/Makassar', (user('TIMEZONE') == 'Asia/Makassar' ? "selected" : null)],
 'Asia/Novokuznetsk' => ['Asia/Novokuznetsk', (user('TIMEZONE') == 'Asia/Novokuznetsk' ? "selected" : null)],
 'Asia/Phnom_Penh' => ['Asia/Phnom_Penh', (user('TIMEZONE') == 'Asia/Phnom_Penh' ? "selected" : null)],
 'Asia/Qostanay' => ['Asia/Qostanay', (user('TIMEZONE') == 'Asia/Qostanay' ? "selected" : null)],
 'Asia/Samarkand' => ['Asia/Samarkand', (user('TIMEZONE') == 'Asia/Samarkand' ? "selected" : null)],
 'Asia/Srednekolymsk' => ['Asia/Srednekolymsk', (user('TIMEZONE') == 'Asia/Srednekolymsk' ? "selected" : null)],
 'Asia/Tehran' => ['Asia/Tehran', (user('TIMEZONE') == 'Asia/Tehran' ? "selected" : null)],
 'Asia/Ulaanbaatar' => ['Asia/Ulaanbaatar', (user('TIMEZONE') == 'Asia/Ulaanbaatar' ? "selected" : null)],
 'Asia/Vladivostok' => ['Asia/Vladivostok', (user('TIMEZONE') == 'Asia/Vladivostok' ? "selected" : null)],
 'Asia/Yerevan' => ['Asia/Yerevan', (user('TIMEZONE') == 'Asia/Yerevan' ? "selected" : null)],
 'Asia/Anadyr' => ['Asia/Anadyr', (user('TIMEZONE') == 'Asia/Anadyr' ? "selected" : null)],
 'Asia/Atyrau' => ['Asia/Atyrau', (user('TIMEZONE') == 'Asia/Atyrau' ? "selected" : null)],
 'Asia/Bangkok' => ['Asia/Bangkok', (user('TIMEZONE') == 'Asia/Bangkok' ? "selected" : null)],
 'Asia/Brunei' => ['Asia/Brunei', (user('TIMEZONE') == 'Asia/Brunei' ? "selected" : null)],
 'Asia/Damascus' => ['Asia/Damascus', (user('TIMEZONE') == 'Asia/Damascus' ? "selected" : null)],
 'Asia/Dushanbe' => ['Asia/Dushanbe', (user('TIMEZONE') == 'Asia/Dushanbe' ? "selected" : null)],
 'Asia/Ho_Chi_Minh' => ['Asia/Ho_Chi_Minh', (user('TIMEZONE') == 'Asia/Ho_Chi_Minh' ? "selected" : null)],
 'Asia/Jakarta' => ['Asia/Jakarta', (user('TIMEZONE') == 'Asia/Jakarta' ? "selected" : null)],
 'Asia/Kamchatka' => ['Asia/Kamchatka', (user('TIMEZONE') == 'Asia/Kamchatka' ? "selected" : null)],
 'Asia/Kolkata' => ['Asia/Kolkata', (user('TIMEZONE') == 'Asia/Kolkata' ? "selected" : null)],
 'Asia/Kuwait' => ['Asia/Kuwait', (user('TIMEZONE') == 'Asia/Kuwait' ? "selected" : null)],
 'Asia/Manila' => ['Asia/Manila', (user('TIMEZONE') == 'Asia/Manila' ? "selected" : null)],
 'Asia/Novosibirsk' => ['Asia/Novosibirsk', (user('TIMEZONE') == 'Asia/Novosibirsk' ? "selected" : null)],
 'Asia/Pontianak' => ['Asia/Pontianak', (user('TIMEZONE') == 'Asia/Pontianak' ? "selected" : null)],
 'Asia/Qyzylorda' => ['Asia/Qyzylorda', (user('TIMEZONE') == 'Asia/Qyzylorda' ? "selected" : null)],
 'Asia/Seoul' => ['Asia/Seoul', (user('TIMEZONE') == 'Asia/Seoul' ? "selected" : null)],
 'Asia/Taipei' => ['Asia/Taipei', (user('TIMEZONE') == 'Asia/Taipei' ? "selected" : null)],
 'Asia/Thimphu' => ['Asia/Thimphu', (user('TIMEZONE') == 'Asia/Thimphu' ? "selected" : null)],
 'Asia/Urumqi' => ['Asia/Urumqi', (user('TIMEZONE') == 'Asia/Urumqi' ? "selected" : null)],
 'Asia/Yakutsk' => ['Asia/Yakutsk', (user('TIMEZONE') == 'Asia/Yakutsk' ? "selected" : null)],
 'Atlantic/Azores' => ['Atlantic/Azores', (user('TIMEZONE') == 'Atlantic/Azores' ? "selected" : null)],
 'Atlantic/Faroe' => ['Atlantic/Faroe', (user('TIMEZONE') == 'Atlantic/Faroe' ? "selected" : null)],
 'Atlantic/St_Helena' => ['Atlantic/St_Helena', (user('TIMEZONE') == 'Atlantic/St_Helena' ? "selected" : null)],
 'Atlantic/Bermuda' => ['Atlantic/Bermuda', (user('TIMEZONE') == 'Atlantic/Bermuda' ? "selected" : null)],
 'Atlantic/Madeira' => ['Atlantic/Madeira', (user('TIMEZONE') == 'Atlantic/Madeira' ? "selected" : null)],
 'Atlantic/Stanley' => ['Atlantic/Stanley', (user('TIMEZONE') == 'Atlantic/Stanley' ? "selected" : null)],
 'Atlantic/Canary' => ['Atlantic/Canary', (user('TIMEZONE') == 'Atlantic/Canary' ? "selected" : null)],
 'Atlantic/Reykjavik' => ['Atlantic/Reykjavik', (user('TIMEZONE') == 'Atlantic/Reykjavik' ? "selected" : null)],
 'Atlantic/Cape_Verde' => ['Atlantic/Cape_Verde', (user('TIMEZONE') == 'Atlantic/Cape_Verde' ? "selected" : null)],
 'Atlantic/South_Georgia' => ['Atlantic/South_Georgia', (user('TIMEZONE') == 'Atlantic/South_Georgia' ? "selected" : null)],
 'Australia/Adelaide' => ['Australia/Adelaide', (user('TIMEZONE') == 'Australia/Adelaide' ? "selected" : null)],
 'Australia/Darwin' => ['Australia/Darwin', (user('TIMEZONE') == 'Australia/Darwin' ? "selected" : null)],
 'Australia/Lord_Howe' => ['Australia/Lord_Howe', (user('TIMEZONE') == 'Australia/Lord_Howe' ? "selected" : null)],
 'Australia/Brisbane' => ['Australia/Brisbane', (user('TIMEZONE') == 'Australia/Brisbane' ? "selected" : null)],
 'Australia/Eucla' => ['Australia/Eucla', (user('TIMEZONE') == 'Australia/Eucla' ? "selected" : null)],
 'Australia/Melbourne' => ['Australia/Melbourne', (user('TIMEZONE') == 'Australia/Melbourne' ? "selected" : null)],
 'Australia/Broken_Hill' => ['Australia/Broken_Hill', (user('TIMEZONE') == 'Australia/Broken_Hill' ? "selected" : null)],
 'Australia/Hobart' => ['Australia/Hobart', (user('TIMEZONE') == 'Australia/Hobart' ? "selected" : null)],
 'Australia/Perth' => ['Australia/Perth', (user('TIMEZONE') == 'Australia/Perth' ? "selected" : null)],
 'Australia/Currie' => ['Australia/Currie', (user('TIMEZONE') == 'Australia/Currie' ? "selected" : null)],
 'Australia/Lindeman' => ['Australia/Lindeman', (user('TIMEZONE') == 'Australia/Lindeman' ? "selected" : null)],
 'Australia/Sydney' => ['Australia/Sydney', (user('TIMEZONE') == 'Australia/Sydney' ? "selected" : null)],
 'Europe/Amsterdam' => ['Europe/Amsterdam', (user('TIMEZONE') == 'Europe/Amsterdam' ? "selected" : null)],
 'Europe/Belgrade' => ['Europe/Belgrade', (user('TIMEZONE') == 'Europe/Belgrade' ? "selected" : null)],
 'Europe/Bucharest' => ['Europe/Bucharest', (user('TIMEZONE') == 'Europe/Bucharest' ? "selected" : null)],
 'Europe/Copenhagen' => ['Europe/Copenhagen', (user('TIMEZONE') == 'Europe/Copenhagen' ? "selected" : null)],
 'Europe/Helsinki' => ['Europe/Helsinki', (user('TIMEZONE') == 'Europe/Helsinki' ? "selected" : null)],
 'Europe/Kaliningrad' => ['Europe/Kaliningrad', (user('TIMEZONE') == 'Europe/Kaliningrad' ? "selected" : null)],
 'Europe/Ljubljana' => ['Europe/Ljubljana', (user('TIMEZONE') == 'Europe/Ljubljana' ? "selected" : null)],
 'Europe/Malta' => ['Europe/Malta', (user('TIMEZONE') == 'Europe/Malta' ? "selected" : null)],
 'Europe/Moscow' => ['Europe/Moscow', (user('TIMEZONE') == 'Europe/Moscow' ? "selected" : null)],
 'Europe/Prague' => ['Europe/Prague', (user('TIMEZONE') == 'Europe/Prague' ? "selected" : null)],
 'Europe/San_Marino' => ['Europe/San_Marino', (user('TIMEZONE') == 'Europe/San_Marino' ? "selected" : null)],
 'Europe/Skopje' => ['Europe/Skopje', (user('TIMEZONE') == 'Europe/Skopje' ? "selected" : null)],
 'Europe/Tirane' => ['Europe/Tirane', (user('TIMEZONE') == 'Europe/Tirane' ? "selected" : null)],
 'Europe/Vatican' => ['Europe/Vatican', (user('TIMEZONE') == 'Europe/Vatican' ? "selected" : null)],
 'Europe/Warsaw' => ['Europe/Warsaw', (user('TIMEZONE') == 'Europe/Warsaw' ? "selected" : null)],
 'Europe/Andorra' => ['Europe/Andorra', (user('TIMEZONE') == 'Europe/Andorra' ? "selected" : null)],
 'Europe/Berlin' => ['Europe/Berlin', (user('TIMEZONE') == 'Europe/Berlin' ? "selected" : null)],
 'Europe/Budapest' => ['Europe/Budapest', (user('TIMEZONE') == 'Europe/Budapest' ? "selected" : null)],
 'Europe/Dublin' => ['Europe/Dublin', (user('TIMEZONE') == 'Europe/Dublin' ? "selected" : null)],
 'Europe/Isle_of_Man' => ['Europe/Isle_of_Man', (user('TIMEZONE') == 'Europe/Isle_of_Man' ? "selected" : null)],
 'Europe/Kiev' => ['Europe/Kiev', (user('TIMEZONE') == 'Europe/Kiev' ? "selected" : null)],
 'Europe/London' => ['Europe/London', (user('TIMEZONE') == 'Europe/London' ? "selected" : null)],
 'Europe/Mariehamn' => ['Europe/Mariehamn', (user('TIMEZONE') == 'Europe/Mariehamn' ? "selected" : null)],
 'Europe/Oslo' => ['Europe/Oslo', (user('TIMEZONE') == 'Europe/Oslo' ? "selected" : null)],
 'Europe/Riga' => ['Europe/Riga', (user('TIMEZONE') == 'Europe/Riga' ? "selected" : null)],
 'Europe/Sarajevo' => ['Europe/Sarajevo', (user('TIMEZONE') == 'Europe/Sarajevo' ? "selected" : null)],
 'Europe/Sofia' => ['Europe/Sofia', (user('TIMEZONE') == 'Europe/Sofia' ? "selected" : null)],
 'Europe/Ulyanovsk' => ['Europe/Ulyanovsk', (user('TIMEZONE') == 'Europe/Ulyanovsk' ? "selected" : null)],
 'Europe/Vienna' => ['Europe/Vienna', (user('TIMEZONE') == 'Europe/Vienna' ? "selected" : null)],
 'Europe/Zagreb' => ['Europe/Zagreb', (user('TIMEZONE') == 'Europe/Zagreb' ? "selected" : null)],
 'Europe/Astrakhan' => ['Europe/Astrakhan', (user('TIMEZONE') == 'Europe/Astrakhan' ? "selected" : null)],
 'Europe/Bratislava' => ['Europe/Bratislava', (user('TIMEZONE') == 'Europe/Bratislava' ? "selected" : null)],
 'Europe/Busingen' => ['Europe/Busingen', (user('TIMEZONE') == 'Europe/Busingen' ? "selected" : null)],
 'Europe/Gibraltar' => ['Europe/Gibraltar', (user('TIMEZONE') == 'Europe/Gibraltar' ? "selected" : null)],
 'Europe/Istanbul' => ['Europe/Istanbul', (user('TIMEZONE') == 'Europe/Istanbul' ? "selected" : null)],
 'Europe/Kirov' => ['Europe/Kirov', (user('TIMEZONE') == 'Europe/Kirov' ? "selected" : null)],
 'Europe/Luxembourg' => ['Europe/Luxembourg', (user('TIMEZONE') == 'Europe/Luxembourg' ? "selected" : null)],
 'Europe/Minsk' => ['Europe/Minsk', (user('TIMEZONE') == 'Europe/Minsk' ? "selected" : null)],
 'Europe/Paris' => ['Europe/Paris', (user('TIMEZONE') == 'Europe/Paris' ? "selected" : null)],
 'Europe/Rome' => ['Europe/Rome', (user('TIMEZONE') == 'Europe/Rome' ? "selected" : null)],
 'Europe/Saratov' => ['Europe/Saratov', (user('TIMEZONE') == 'Europe/Saratov' ? "selected" : null)],
 'Europe/Stockholm' => ['Europe/Stockholm', (user('TIMEZONE') == 'Europe/Stockholm' ? "selected" : null)],
 'Europe/Uzhgorod' => ['Europe/Uzhgorod', (user('TIMEZONE') == 'Europe/Uzhgorod' ? "selected" : null)],
 'Europe/Vilnius' => ['Europe/Vilnius', (user('TIMEZONE') == 'Europe/Vilnius' ? "selected" : null)],
 'Europe/Zaporozhye' => ['Europe/Zaporozhye', (user('TIMEZONE') == 'Europe/Zaporozhye' ? "selected" : null)],
 'Europe/Athens' => ['Europe/Athens', (user('TIMEZONE') == 'Europe/Athens' ? "selected" : null)],
 'Europe/Brussels' => ['Europe/Brussels', (user('TIMEZONE') == 'Europe/Brussels' ? "selected" : null)],
 'Europe/Chisinau' => ['Europe/Chisinau', (user('TIMEZONE') == 'Europe/Chisinau' ? "selected" : null)],
 'Europe/Guernsey' => ['Europe/Guernsey', (user('TIMEZONE') == 'Europe/Guernsey' ? "selected" : null)],
 'Europe/Jersey' => ['Europe/Jersey', (user('TIMEZONE') == 'Europe/Jersey' ? "selected" : null)],
 'Europe/Lisbon' => ['Europe/Lisbon', (user('TIMEZONE') == 'Europe/Lisbon' ? "selected" : null)],
 'Europe/Madrid' => ['Europe/Madrid', (user('TIMEZONE') == 'Europe/Madrid' ? "selected" : null)],
 'Europe/Monaco' => ['Europe/Monaco', (user('TIMEZONE') == 'Europe/Monaco' ? "selected" : null)],
 'Europe/Podgorica' => ['Europe/Podgorica', (user('TIMEZONE') == 'Europe/Podgorica' ? "selected" : null)],
 'Europe/Samara' => ['Europe/Samara', (user('TIMEZONE') == 'Europe/Samara' ? "selected" : null)],
 'Europe/Simferopol' => ['Europe/Simferopol', (user('TIMEZONE') == 'Europe/Simferopol' ? "selected" : null)],
 'Europe/Tallinn' => ['Europe/Tallinn', (user('TIMEZONE') == 'Europe/Tallinn' ? "selected" : null)],
 'Europe/Vaduz' => ['Europe/Vaduz', (user('TIMEZONE') == 'Europe/Vaduz' ? "selected" : null)],
 'Europe/Volgograd' => ['Europe/Volgograd', (user('TIMEZONE') == 'Europe/Volgograd' ? "selected" : null)],
 'Europe/Zurich' => ['Europe/Zurich', (user('TIMEZONE') == 'Europe/Zurich' ? "selected" : null)]
), 'Временная зона по умолчанию', 'form-control-100-modify-select', 'clock-o')?>  
<?=html::button('button ajax-button', 'ok_tm', 'save', 'Сохранить изменения')?>
</form>
</div>
<?

back('/account/settings/');
acms_footer();